-- Zomato Restaurant Analytics — source-backed MySQL table
-- This replaces the old assumption that the restaurant source is split across
-- customers/orders/reviews tables. The uploaded source is one restaurant-level dataset.

CREATE DATABASE IF NOT EXISTS zomato_analytics;
USE zomato_analytics;

DROP TABLE IF EXISTS zomato_restaurants_clean;

CREATE TABLE zomato_restaurants_clean (
    source_row_id INT,
    sno INT,
    zomato_url VARCHAR(500) NOT NULL,
    name VARCHAR(255),
    city VARCHAR(100),
    area VARCHAR(150),
    rating_raw VARCHAR(20),
    rating_clean DECIMAL(3,2),
    rating_count INT,
    telephone VARCHAR(255),
    cuisine VARCHAR(500),
    cost_for_two_raw VARCHAR(50),
    cost_for_two_clean DECIMAL(10,2),
    address TEXT,
    coordinates VARCHAR(100),
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    timings TEXT,
    online_order BOOLEAN,
    table_reservation BOOLEAN,
    delivery_only BOOLEAN,
    famous_food TEXT,
    coordinate_valid BOOLEAN,
    has_rating BOOLEAN,
    has_cost BOOLEAN,
    PRIMARY KEY (zomato_url)
);

-- Import the processed CSV generated by Python/02_clean_restaurant_data.py.
-- Adjust the local file path and LOCAL INFILE setting for your MySQL installation.
-- The source file itself is intentionally kept separate from this cleaned table.

-- Example:
-- LOAD DATA LOCAL INFILE '../Data/processed/zomato_restaurants_clean.csv'
-- INTO TABLE zomato_restaurants_clean
-- FIELDS TERMINATED BY ',' ENCLOSED BY '"'
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS;

-- Post-load QA
SELECT COUNT(*) AS restaurant_rows,
       COUNT(DISTINCT zomato_url) AS unique_restaurants,
       SUM(has_rating) AS rated_restaurants,
       SUM(has_cost) AS usable_cost_records,
       SUM(coordinate_valid) AS valid_coordinates
FROM zomato_restaurants_clean;
